packages:
  - .

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - bcrypt
  - chromedriver
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
