packages:
  - .
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - bcrypt
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
overrides:
  prismjs@<1.30.0: '>=1.30.0'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
