packages:
  - .

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - bcrypt
  - chromedriver
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  diff@>=4.0.0 <4.0.4: '>=4.0.4'
  fast-xml-parser@>=5.0.9 <=5.3.3: '>=5.3.4'
  jws@<3.2.3: '>=3.2.3'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  preact@>=10.27.0 <10.27.3: '>=10.27.3'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  tmp@<=0.2.3: '>=0.2.4'
  undici@<6.23.0: '>=6.23.0'
  webpack@>=5.49.0 <5.104.0: '>=5.104.0'
  webpack@>=5.49.0 <=5.104.0: '>=5.104.1'
