export interface ServiceArea {
  slug: string
  cityName: string
  title: string
  description: string
  keywords: string[]
}

/*
 * Central list of towns/cities within ~40 mi of ZIP 77591.
 * Add or edit entries here and the dynamic [slug] page will update automatically.
 */
export const SERVICE_AREAS: ServiceArea[] = [
  {
    slug: "clear-lake-city",
    cityName: "Clear Lake City",
    title: "Mobile Notary in Clear Lake City | Houston Mobile Notary Pros",
    description:
      "On-demand mobile notary services throughout Clear Lake City, TX. We travel to your home, office, or coffee shop—7 days a week.",
    keywords: [
      "mobile notary Clear Lake City",
      "after-hours mobile notary Clear Lake City",
      "same-day notary Clear Lake City",
      "Clear Lake City loan signing agent",
      "traveling notary Clear Lake City",
      "24 hour notary Clear Lake City",
      "apostille services Clear Lake City",
      "mobile notary 77058",
      "notary near NASA Johnson Space Center",
      "emergency notary Clear Lake City",
      "weekend notary Clear Lake City",
      "on-site notary Clear Lake City",
    ],
  },
  {
    slug: "pasadena",
    cityName: "Pasadena",
    title: "Mobile Notary in Pasadena, TX | Houston Mobile Notary Pros",
    description:
      "Fast, friendly notarization anywhere in Pasadena—loan signings, POAs, real-estate documents, and more.",
    keywords: [
      "mobile notary Pasadena",
      "after-hours mobile notary Pasadena TX",
      "same-day notary Pasadena TX",
      "Pasadena TX loan signing agent",
      "traveling notary Pasadena",
      "24 hour notary Pasadena TX",
      "apostille services Pasadena TX",
      "mobile notary 77502",
      "notary near Strawberry Park",
      "emergency notary Pasadena",
      "weekend notary Pasadena",
      "on-site notary Pasadena",
    ],
  },
  {
    slug: "texas-city",
    cityName: "Texas City",
    title: "Mobile Notary in Texas City | Houston Mobile Notary Pros",
    description:
      "Texas City-based notary ready to travel within 20 miles of 77591 for convenient, accurate signings.",
    keywords: [
      "mobile notary Texas City",
      "after-hours mobile notary Texas City",
      "same-day notary Texas City",
      "Texas City loan signing agent",
      "traveling notary Texas City",
      "24 hour notary Texas City",
      "apostille services Texas City",
      "mobile notary 77591",
      "notary near Texas City Dike",
      "emergency notary Texas City",
      "weekend notary Texas City",
      "on-site notary Texas City",
    ],
  },
  {
    slug: "webster",
    cityName: "Webster",
    title: "Mobile Notary in Webster, TX | Houston Mobile Notary Pros",
    description: "Same-day mobile notarization across Webster and the Clear Lake area.",
    keywords: [
      "mobile notary Webster",
      "after-hours mobile notary Webster",
      "same-day notary Webster TX",
      "Webster TX loan signing agent",
      "traveling notary Webster",
      "24 hour notary Webster TX",
      "apostille services Webster TX",
      "mobile notary 77598",
      "notary near NASA Parkway",
      "emergency notary Webster",
      "weekend notary Webster",
      "on-site notary Webster",
    ],
  },
  {
    slug: "nassau-bay",
    cityName: "Nassau Bay",
    title: "Mobile Notary in Nassau Bay | Houston Mobile Notary Pros",
    description: "Professional traveling notary service for Nassau Bay residents and businesses.",
    keywords: [
      "mobile notary Nassau Bay",
      "after-hours mobile notary Nassau Bay",
      "same-day notary Nassau Bay TX",
      "Nassau Bay loan signing agent",
      "traveling notary Nassau Bay",
      "24 hour notary Nassau Bay",
      "apostille services Nassau Bay",
      "mobile notary 77058",
      "notary near Space Center Houston",
      "emergency notary Nassau Bay",
      "weekend notary Nassau Bay",
      "on-site notary Nassau Bay",
    ],
  },
  {
    slug: "seabrook",
    cityName: "Seabrook",
    title: "Mobile Notary in Seabrook, TX | Houston Mobile Notary Pros",
    description: "We come to you in Seabrook—home, marina, or office.",
    keywords: [
      "mobile notary Seabrook",
      "after-hours mobile notary Seabrook",
      "same-day notary Seabrook TX",
      "Seabrook TX loan signing agent",
      "traveling notary Seabrook",
      "24 hour notary Seabrook TX",
      "apostille services Seabrook TX",
      "mobile notary 77586",
      "notary near Kemah Boardwalk",
      "emergency notary Seabrook",
      "weekend notary Seabrook",
      "on-site notary Seabrook",
    ],
  },
  {
    slug: "clear-lake-shores",
    cityName: "Clear Lake Shores",
    title: "Mobile Notary in Clear Lake Shores | Houston Mobile Notary Pros",
    description: "Boat-friendly notary that meets you dock-side in Clear Lake Shores.",
    keywords: [
      "mobile notary Clear Lake Shores",
      "after-hours mobile notary Clear Lake Shores",
      "same-day notary Clear Lake Shores",
      "Clear Lake Shores loan signing agent",
      "traveling notary Clear Lake Shores",
      "24 hour notary Clear Lake Shores",
      "apostille services Clear Lake Shores",
      "mobile notary 77565",
      "notary near Jarboe Bayou Park",
      "emergency notary Clear Lake Shores",
      "weekend notary Clear Lake Shores",
      "on-site notary Clear Lake Shores",
    ],
  },
  {
    slug: "taylor-lake-village",
    cityName: "Taylor Lake Village",
    title: "Mobile Notary in Taylor Lake Village | Houston Mobile Notary Pros",
    description: "Prompt, precise notarization services in Taylor Lake Village.",
    keywords: [
      "mobile notary Taylor Lake Village",
      "after-hours mobile notary Taylor Lake Village",
      "same-day notary Taylor Lake Village",
      "Taylor Lake Village loan signing agent",
      "traveling notary Taylor Lake Village",
      "24 hour notary Taylor Lake Village",
      "apostille services Taylor Lake Village",
      "mobile notary 77586",
      "notary near Clear Lake Park",
      "emergency notary Taylor Lake Village",
      "weekend notary Taylor Lake Village",
      "on-site notary Taylor Lake Village",
    ],
  },
  {
    slug: "friendswood",
    cityName: "Friendswood",
    title: "Mobile Notary in Friendswood | Houston Mobile Notary Pros",
    description: "Convenient mobile notary public serving Friendswood.",
    keywords: [
      "mobile notary Friendswood",
      "after-hours mobile notary Friendswood",
      "same-day notary Friendswood",
      "Friendswood loan signing agent",
      "traveling notary Friendswood",
      "24 hour notary Friendswood",
      "apostille services Friendswood",
      "mobile notary 77546",
      "notary near Stevenson Park",
      "emergency notary Friendswood",
      "weekend notary Friendswood",
      "on-site notary Friendswood",
    ],
  },
  {
    slug: "league-city",
    cityName: "League City",
    title: "Mobile Notary in League City | Houston Mobile Notary Pros",
    description: "Trusted traveling notary for League City residents and businesses.",
    keywords: [
      "mobile notary League City",
      "after-hours mobile notary League City",
      "same-day notary League City",
      "League City loan signing agent",
      "traveling notary League City",
      "24 hour notary League City",
      "apostille services League City",
      "mobile notary 77573",
      "notary near Walter Hall Park",
      "emergency notary League City",
      "weekend notary League City",
      "on-site notary League City",
    ],
  },
  {
    slug: "kemah",
    cityName: "Kemah",
    title: "Mobile Notary in Kemah | Houston Mobile Notary Pros",
    description: "Mobile notary that meets you along the Kemah Boardwalk and beyond.",
    keywords: [
      "mobile notary Kemah",
      "after-hours mobile notary Kemah",
      "same-day notary Kemah",
      "Kemah loan signing agent",
      "traveling notary Kemah",
      "24 hour notary Kemah",
      "apostille services Kemah",
      "mobile notary 77565",
      "notary near Kemah Boardwalk",
      "emergency notary Kemah",
      "weekend notary Kemah",
      "on-site notary Kemah",
    ],
  },
  {
    slug: "la-porte",
    cityName: "La Porte",
    title: "Mobile Notary in La Porte | Houston Mobile Notary Pros",
    description: "Dependable mobile notary serving La Porte, TX.",
    keywords: [
      "mobile notary La Porte",
      "after-hours mobile notary La Porte",
      "same-day notary La Porte",
      "La Porte loan signing agent",
      "traveling notary La Porte",
      "24 hour notary La Porte",
      "apostille services La Porte",
      "mobile notary 77571",
      "notary near Sylvan Beach Park",
      "emergency notary La Porte",
      "weekend notary La Porte",
      "on-site notary La Porte",
    ],
  },
  {
    slug: "deer-park",
    cityName: "Deer Park",
    title: "Mobile Notary in Deer Park | Houston Mobile Notary Pros",
    description: "On-site notarizations throughout Deer Park, TX.",
    keywords: [
      "mobile notary Deer Park",
      "after-hours mobile notary Deer Park",
      "same-day notary Deer Park",
      "Deer Park loan signing agent",
      "traveling notary Deer Park",
      "24 hour notary Deer Park",
      "apostille services Deer Park",
      "mobile notary 77536",
      "notary near Battleground Golf Course",
      "emergency notary Deer Park",
      "weekend notary Deer Park",
      "on-site notary Deer Park",
    ],
  },
  {
    slug: "south-houston",
    cityName: "South Houston",
    title: "Mobile Notary in South Houston | Houston Mobile Notary Pros",
    description: "We travel to homes, offices, and hospitals in South Houston for fast notarizations.",
    keywords: [
      "mobile notary South Houston",
      "after-hours mobile notary South Houston",
      "same-day notary South Houston",
      "South Houston loan signing agent",
      "traveling notary South Houston",
      "24 hour notary South Houston",
      "apostille services South Houston",
      "mobile notary 77587",
      "notary near Cristo Rey Catholic Church",
      "emergency notary South Houston",
      "weekend notary South Houston",
      "on-site notary South Houston",
    ],
  },
  {
    slug: "la-marque",
    cityName: "La Marque",
    title: "Mobile Notary in La Marque | Houston Mobile Notary Pros",
    description: "Reliable notary public on wheels for La Marque.",
    keywords: [
      "mobile notary La Marque",
      "after-hours mobile notary La Marque",
      "same-day notary La Marque",
      "La Marque loan signing agent",
      "traveling notary La Marque",
      "24 hour notary La Marque",
      "apostille services La Marque",
      "mobile notary 77568",
      "notary near Gulf Greyhound Park",
      "emergency notary La Marque",
      "weekend notary La Marque",
      "on-site notary La Marque",
    ],
  },
  {
    slug: "dickinson",
    cityName: "Dickinson",
    title: "Mobile Notary in Dickinson, TX | Houston Mobile Notary Pros",
    description: "Mobile notary services for Dickinson residents—7 days a week.",
    keywords: [
      "mobile notary Dickinson",
      "after-hours mobile notary Dickinson",
      "same-day notary Dickinson",
      "Dickinson loan signing agent",
      "traveling notary Dickinson",
      "24 hour notary Dickinson",
      "apostille services Dickinson",
      "mobile notary 77539",
      "notary near Dickinson Bayou",
      "emergency notary Dickinson",
      "weekend notary Dickinson",
      "on-site notary Dickinson",
    ],
  },
  {
    slug: "santa-fe",
    cityName: "Santa Fe",
    title: "Mobile Notary in Santa Fe, TX | Houston Mobile Notary Pros",
    description: "Prompt notarization anywhere in Santa Fe and surrounding rural areas.",
    keywords: [
      "mobile notary Santa Fe",
      "after-hours mobile notary Santa Fe",
      "same-day notary Santa Fe",
      "Santa Fe TX loan signing agent",
      "traveling notary Santa Fe",
      "24 hour notary Santa Fe",
      "apostille services Santa Fe TX",
      "mobile notary 77510",
      "notary near Haak Vineyards",
      "emergency notary Santa Fe TX",
      "weekend notary Santa Fe",
      "on-site notary Santa Fe TX",
    ],
  },
  {
    slug: "galveston",
    cityName: "Galveston",
    title: "Mobile Notary in Galveston | Houston Mobile Notary Pros",
    description: "Island-wide mobile notary—hotels, cruise terminals, hospitals, and homes in Galveston.",
    keywords: [
      "mobile notary Galveston",
      "after-hours mobile notary Galveston",
      "same-day notary Galveston",
      "Galveston loan signing agent",
      "traveling notary Galveston",
      "24 hour notary Galveston",
      "apostille services Galveston",
      "mobile notary 77550",
      "notary near Pleasure Pier",
      "emergency notary Galveston",
      "weekend notary Galveston",
      "on-site notary Galveston",
    ],
  },
  {
    slug: "pearland",
    cityName: "Pearland",
    title: "Mobile Notary in Pearland | Houston Mobile Notary Pros",
    description: "From Shadow Creek Ranch to Pearland Town Center, we deliver same-day notarization across Pearland’s 77584, 77581, and 77588 ZIP codes—loan signings, POAs, wills, and more.",
    keywords: [
      "mobile notary Pearland",
      "after-hours mobile notary Pearland",
      "same-day notary Pearland TX",
      "Pearland loan signing agent",
      "traveling notary Pearland",
      "24 hour notary Pearland",
      "apostille services Pearland TX",
      "mobile notary 77584",
      "notary near Pearland Town Center",
      "emergency notary Pearland",
      "weekend notary Pearland",
      "on-site notary Pearland",
    ],
  },
  {
    slug: "alvin",
    cityName: "Alvin",
    title: "Mobile Notary in Alvin, TX | Houston Mobile Notary Pros",
    description: "Reliable mobile notary public serving Alvin 77511—real-estate closings, I-9 verifications, power of attorney notarization, and more.",
    keywords: [
      "mobile notary Alvin TX",
      "after-hours mobile notary Alvin",
      "same-day notary Alvin",
      "Alvin loan signing agent",
      "traveling notary Alvin",
      "24 hour notary Alvin",
      "apostille services Alvin TX",
      "mobile notary 77511",
      "notary near Nolan Ryan Museum",
      "emergency notary Alvin",
      "weekend notary Alvin",
      "on-site notary Alvin",
    ],
  },
  {
    slug: "manvel",
    cityName: "Manvel",
    title: "Mobile Notary in Manvel, TX | Houston Mobile Notary Pros",
    description: "Fast loan-signing and document notarization throughout Manvel 77578—including evening and weekend appointments.",
    keywords: [
      "mobile notary Manvel TX",
      "after-hours mobile notary Manvel",
      "same-day notary Manvel",
      "Manvel loan signing agent",
      "traveling notary Manvel",
      "24 hour notary Manvel",
      "apostille services Manvel TX",
      "mobile notary 77578",
      "notary near Manvel Town Center",
      "emergency notary Manvel",
      "weekend notary Manvel",
      "on-site notary Manvel",
    ],
  },
  {
    slug: "hitchcock",
    cityName: "Hitchcock",
    title: "Mobile Notary in Hitchcock, TX | Houston Mobile Notary Pros",
    description: "On-site notarization in Hitchcock 77563—power of attorney, real estate, and more, delivered to your door or Jack Brooks Park.",
    keywords: [
      "mobile notary Hitchcock TX",
      "after-hours mobile notary Hitchcock",
      "same-day notary Hitchcock",
      "Hitchcock loan signing agent",
      "traveling notary Hitchcock",
      "24 hour notary Hitchcock",
      "apostille services Hitchcock TX",
      "mobile notary 77563",
      "notary near Jack Brooks Park",
      "emergency notary Hitchcock",
      "weekend notary Hitchcock",
      "on-site notary Hitchcock",
    ],
  },
  {
    slug: "brazoria-county",
    cityName: "Brazoria County",
    title: "Mobile Notary in Brazoria County | Houston Mobile Notary Pros",
    description: "County-wide traveling notary—Alvin, Manvel, Pearland, and rural areas—covering affidavits, estate docs, and loan packages.",
    keywords: [
      "mobile notary Brazoria County",
      "after-hours mobile notary Brazoria County",
      "same-day notary Brazoria County",
      "Brazoria County loan signing agent",
      "traveling notary Brazoria County",
      "24 hour notary Brazoria County",
      "apostille services Brazoria County",
      "notary near Brazoria National Wildlife Refuge",
      "emergency notary Brazoria County",
      "weekend notary Brazoria County",
      "on-site notary Brazoria County",
      "mobile notary Brazoria TX",
    ],
  },
  {
    slug: "baytown",
    cityName: "Baytown",
    title: "Mobile Notary in Baytown, TX | Houston Mobile Notary Pros",
    description: "Certified mobile notaries for Baytown—serving refineries, hospitals, and waterfront neighborhoods with rapid response.",
    keywords: [
      "mobile notary Baytown",
      "notary near me Baytown",
      "Baytown loan signing agent",
      "after-hours mobile notary Baytown",
      "same-day notary Baytown",
      "traveling notary Baytown TX",
      "apostille services Baytown",
      "mobile notary 77520",
      "mobile notary 77521",
      "mobile notary 77523",
      "notary near Baytown Nature Center",
      "emergency notary Baytown",
      "weekend notary Baytown",
    ],
  },
  {
    slug: "channelview",
    cityName: "Channelview",
    title: "Mobile Notary in Channelview, TX | Houston Mobile Notary Pros",
    description: "On-demand mobile notarization throughout Channelview—refinery corridor, Sheldon Lake, and the entire 77530 ZIP code.",
    keywords: [
      "mobile notary Channelview",
      "Channelview loan signing agent",
      "notary near me Channelview",
      "after-hours notary Channelview",
      "same-day notary Channelview",
      "traveling notary Channelview TX",
      "mobile notary 77530",
      "notary near San Jacinto River",
      "emergency notary Channelview",
      "weekend notary Channelview",
    ],
  },
  {
    slug: "humble",
    cityName: "Humble",
    title: "Mobile Notary in Humble, TX | Houston Mobile Notary Pros",
    description: "Professional mobile notary service for Humble, Atascocita, and Lake Houston communities—loan signings, POAs, and more.",
    keywords: [
      "mobile notary Humble",
      "notary near me Humble",
      "Humble loan signing agent",
      "after-hours notary Humble",
      "same-day notary Humble",
      "traveling notary Humble TX",
      "mobile notary 77338",
      "mobile notary 77346",
      "mobile notary 77396",
      "notary near Deerbrook Mall",
      "emergency notary Humble",
    ],
  },
  {
    slug: "kingwood",
    cityName: "Kingwood",
    title: "Mobile Notary in Kingwood, TX | Houston Mobile Notary Pros",
    description: "Forest-section coverage across Kingwood—East End Park, Kings Harbor, and village clubhouses with appointment reminders.",
    keywords: [
      "mobile notary Kingwood",
      "notary near me Kingwood",
      "Kingwood loan signing agent",
      "after-hours notary Kingwood",
      "same-day notary Kingwood",
      "traveling notary Kingwood TX",
      "mobile notary 77339",
      "mobile notary 77345",
      "notary near Kingwood Town Center",
      "emergency notary Kingwood",
    ],
  },
  {
    slug: "katy",
    cityName: "Katy",
    title: "Mobile Notary in Katy, TX | Houston Mobile Notary Pros",
    description: "Serving Old Katy, Cinco Ranch, and Energy Corridor commuters with fast mobile notarization and loan closing support.",
    keywords: [
      "mobile notary Katy",
      "notary near me Katy",
      "Katy loan signing agent",
      "traveling notary Katy TX",
      "after-hours notary Katy",
      "same-day notary Katy",
      "mobile notary 77449",
      "mobile notary 77450",
      "mobile notary 77494",
      "notary near Katy Mills",
      "emergency notary Katy",
      "weekend notary Katy",
    ],
  },
  {
    slug: "cypress",
    cityName: "Cypress",
    title: "Mobile Notary in Cypress, TX | Houston Mobile Notary Pros",
    description: "Cypress households and businesses rely on us for evening notarization—Towne Lake, Bridgeland, Fairfield, and beyond.",
    keywords: [
      "mobile notary Cypress",
      "notary near me Cypress",
      "Cypress TX loan signing agent",
      "after-hours notary Cypress",
      "same-day notary Cypress",
      "traveling notary Cypress TX",
      "mobile notary 77429",
      "mobile notary 77433",
      "notary near Towne Lake Boardwalk",
      "emergency notary Cypress",
    ],
  },
  {
    slug: "spring",
    cityName: "Spring",
    title: "Mobile Notary in Spring, TX | Houston Mobile Notary Pros",
    description: "Mobile notary for Spring, Old Town Spring, and The Woodlands corridor—available mornings, evenings, and weekends.",
    keywords: [
      "mobile notary Spring TX",
      "notary near me Spring",
      "Spring loan signing agent",
      "after-hours notary Spring",
      "same-day notary Spring",
      "traveling notary Spring TX",
      "mobile notary 77373",
      "mobile notary 77379",
      "mobile notary 77388",
      "notary near Old Town Spring",
      "emergency notary Spring",
    ],
  },
  {
    slug: "tomball",
    cityName: "Tomball",
    title: "Mobile Notary in Tomball, TX | Houston Mobile Notary Pros",
    description: "Certified notaries dispatched across Tomball—historic downtown, Creekside Park, and surrounding acreage homes.",
    keywords: [
      "mobile notary Tomball",
      "notary near me Tomball",
      "Tomball loan signing agent",
      "after-hours notary Tomball",
      "same-day notary Tomball",
      "traveling notary Tomball TX",
      "mobile notary 77375",
      "mobile notary 77377",
      "notary near Tomball Regional Medical Center",
      "emergency notary Tomball",
    ],
  },
  {
    slug: "richmond",
    cityName: "Richmond",
    title: "Mobile Notary in Richmond, TX | Houston Mobile Notary Pros",
    description: "On-site notarization for Richmond and Pecan Grove—estate planning, loan signings, and hospital visits on demand.",
    keywords: [
      "mobile notary Richmond TX",
      "notary near me Richmond",
      "Richmond loan signing agent",
      "after-hours notary Richmond",
      "same-day notary Richmond",
      "traveling notary Richmond TX",
      "mobile notary 77469",
      "mobile notary 77406",
      "mobile notary 77407",
      "notary near George Ranch",
      "emergency notary Richmond",
    ],
  },
  {
    slug: "rosenberg",
    cityName: "Rosenberg",
    title: "Mobile Notary in Rosenberg, TX | Houston Mobile Notary Pros",
    description: "Rapid-response mobile notary for Rosenberg businesses, distribution centers, and residential neighborhoods.",
    keywords: [
      "mobile notary Rosenberg",
      "notary near me Rosenberg",
      "Rosenberg loan signing agent",
      "after-hours notary Rosenberg",
      "same-day notary Rosenberg",
      "traveling notary Rosenberg TX",
      "mobile notary 77471",
      "notary near Brazos Town Center",
      "emergency notary Rosenberg",
      "weekend notary Rosenberg",
    ],
  },
  {
    slug: "houston",
    cityName: "Houston",
    title: "Mobile Notary in Houston, TX | Houston Mobile Notary Pros",
    description: "Professional mobile notary services throughout Houston - downtown, medical center, and all neighborhoods. We come to you 24/7 for loan signings, POAs, and document notarization.",
    keywords: [
      "mobile notary Houston",
      "notary near me Houston",
      "Houston mobile notary service",
      "downtown Houston notary",
      "Houston loan signing agent",
      "traveling notary Houston TX",
      "24 hour notary Houston",
      "emergency notary Houston",
      "mobile notary 77002",
      "mobile notary 77004", 
      "mobile notary 77019",
      "mobile notary 77005",
      "Houston notary public",
      "same day notary Houston",
      "weekend notary Houston",
      "medical center notary Houston",
    ],
  },
  {
    slug: "sugar-land",
    cityName: "Sugar Land",
    title: "Mobile Notary in Sugar Land, TX | Houston Mobile Notary Pros",
    description: "Premium mobile notary services in Sugar Land - First Colony, New Territory, Greatwood, and all Sugar Land communities. Fast, professional, reliable.",
    keywords: [
      "mobile notary Sugar Land",
      "notary near me Sugar Land",
      "Sugar Land mobile notary",
      "Sugar Land loan signing agent",
      "traveling notary Sugar Land",
      "24 hour notary Sugar Land",
      "mobile notary 77479",
      "mobile notary 77478",
      "mobile notary 77496",
      "notary near First Colony",
      "emergency notary Sugar Land",
      "weekend notary Sugar Land",
      "Sugar Land notary public",
    ],
  },
  {
    slug: "missouri-city",
    cityName: "Missouri City",
    title: "Mobile Notary in Missouri City, TX | Houston Mobile Notary Pros", 
    description: "Convenient mobile notary services throughout Missouri City - Sienna Plantation, Riverstone, and all Missouri City neighborhoods. We travel to you!",
    keywords: [
      "mobile notary Missouri City",
      "notary near me Missouri City",
      "Missouri City mobile notary",
      "Missouri City loan signing agent",
      "traveling notary Missouri City",
      "24 hour notary Missouri City",
      "mobile notary 77459",
      "mobile notary 77489",
      "notary near Sienna Plantation",
      "emergency notary Missouri City",
      "weekend notary Missouri City",
      "Missouri City notary public",
    ],
  },
  {
    slug: "stafford",
    cityName: "Stafford",
    title: "Mobile Notary in Stafford, TX | Houston Mobile Notary Pros",
    description: "Professional mobile notary services in Stafford - homes, offices, and businesses. Same-day service available throughout 77477.",
    keywords: [
      "mobile notary Stafford",
      "notary near me Stafford",
      "Stafford mobile notary",
      "Stafford TX loan signing agent", 
      "traveling notary Stafford",
      "24 hour notary Stafford",
      "mobile notary 77477",
      "emergency notary Stafford",
      "weekend notary Stafford",
      "Stafford notary public",
    ],
  },
  {
    slug: "the-woodlands",
    cityName: "The Woodlands",
    title: "Mobile Notary in The Woodlands, TX | Houston Mobile Notary Pros",
    description: "Certified mobile notaries serving The Woodlands—Market Street, Hughes Landing, Sterling Ridge, and all villages—with evening and weekend availability.",
    keywords: [
      "mobile notary The Woodlands",
      "notary near me The Woodlands",
      "The Woodlands loan signing agent",
      "traveling notary The Woodlands",
      "after-hours notary The Woodlands",
      "same-day notary The Woodlands",
      "mobile notary 77380",
      "mobile notary 77381",
      "mobile notary 77382",
      "notary near The Woodlands Mall",
      "emergency notary The Woodlands",
    ],
  },
  {
    slug: "river-oaks",
    cityName: "River Oaks",
    title: "Mobile Notary in River Oaks | Houston Mobile Notary Pros",
    description: "On-call notaries for River Oaks, Afton Oaks, and Highland Village—perfect for estate signings, real-estate closings, and corporate documents.",
    keywords: [
      "mobile notary River Oaks",
      "notary near me River Oaks",
      "River Oaks loan signing agent",
      "traveling notary River Oaks",
      "after-hours notary River Oaks",
      "same-day notary River Oaks",
      "mobile notary 77019",
      "mobile notary 77027",
      "notary near River Oaks District",
      "emergency notary River Oaks",
    ],
  },
  {
    slug: "west-university",
    cityName: "West University Place",
    title: "Mobile Notary in West University Place | Houston Mobile Notary Pros",
    description: "Mobile notary public covering West University Place, Southside Place, and Rice Village with hospital, campus, and in-home appointments.",
    keywords: [
      "mobile notary West University",
      "notary near me West University Place",
      "West University loan signing agent",
      "traveling notary West University",
      "after-hours notary West U",
      "same-day notary West University",
      "mobile notary 77005",
      "mobile notary 77030",
      "notary near Rice University",
      "emergency notary West University",
    ],
  },
  {
    slug: "bellaire",
    cityName: "Bellaire",
    title: "Mobile Notary in Bellaire, TX | Houston Mobile Notary Pros",
    description: "Doorstep notarization for Bellaire businesses, medical offices, and residential estates—available 7 days a week.",
    keywords: [
      "mobile notary Bellaire",
      "notary near me Bellaire",
      "Bellaire loan signing agent",
      "traveling notary Bellaire",
      "after-hours notary Bellaire",
      "same-day notary Bellaire",
      "mobile notary 77401",
      "mobile notary 77081",
      "notary near Evelyn's Park",
      "emergency notary Bellaire",
    ],
  },
  {
    slug: "midtown-houston",
    cityName: "Midtown Houston",
    title: "Mobile Notary in Midtown Houston | Houston Mobile Notary Pros",
    description: "Fast mobile notarization in Midtown Houston—apartments, co-working spaces, and law offices between Downtown and the Museum District.",
    keywords: [
      "mobile notary Midtown Houston",
      "notary near me Midtown Houston",
      "Midtown Houston loan signing agent",
      "traveling notary Midtown",
      "after-hours notary Midtown Houston",
      "same-day notary Midtown Houston",
      "mobile notary 77002",
      "mobile notary 77006",
      "notary near Midtown Park",
      "emergency notary Midtown Houston",
    ],
  },
  {
    slug: "medical-center",
    cityName: "Texas Medical Center",
    title: "Mobile Notary in the Texas Medical Center | Houston Mobile Notary Pros",
    description: "On-call medical notarization for Houston’s Texas Medical Center—hospitals, research towers, and patient housing with rapid response.",
    keywords: [
      "mobile notary Texas Medical Center",
      "notary near me medical center Houston",
      "medical center loan signing agent",
      "traveling notary Texas Medical Center",
      "after-hours notary medical center Houston",
      "same-day notary medical center Houston",
      "mobile notary 77030",
      "mobile notary 77054",
      "notary near MD Anderson",
      "hospital notary Houston",
    ],
  },
  {
    slug: "houston-heights",
    cityName: "Houston Heights",
    title: "Mobile Notary in The Heights | Houston Mobile Notary Pros",
    description: "Serving Houston Heights, Woodland Heights, and Shady Acres with flexible evening and weekend mobile notary appointments.",
    keywords: [
      "mobile notary Houston Heights",
      "notary near me Heights Houston",
      "Heights loan signing agent",
      "traveling notary Houston Heights",
      "after-hours notary Heights Houston",
      "same-day notary Heights Houston",
      "mobile notary 77008",
      "mobile notary 77009",
      "notary near Heights Mercantile",
      "emergency notary Houston Heights",
    ],
  },
]

export function getServiceAreaBySlug(slug: string): ServiceArea | undefined {
  return SERVICE_AREAS.find((a) => a.slug === slug)
}
