export interface ServiceArea {
  slug: string
  cityName: string
  title: string
  description: string
  keywords: string[]
}

/*
 * Central list of towns/cities within ~40 mi of ZIP 77591.
 * Add or edit entries here and the dynamic [slug] page will update automatically.
 */
export const SERVICE_AREAS: ServiceArea[] = [
  {
    slug: "clear-lake-city",
    cityName: "Clear Lake City",
    title: "Mobile Notary in Clear Lake City | Houston Mobile Notary Pros",
    description:
      "On-demand mobile notary services throughout Clear Lake City, TX. We travel to your home, office, or coffee shop—7 days a week.",
    keywords: [
      "mobile notary Clear Lake City",
      "after-hours mobile notary Clear Lake City",
      "same-day notary Clear Lake City",
      "Clear Lake City loan signing agent",
      "traveling notary Clear Lake City",
      "24 hour notary Clear Lake City",
      "apostille services Clear Lake City",
      "mobile notary 77058",
      "notary near NASA Johnson Space Center",
      "emergency notary Clear Lake City",
      "weekend notary Clear Lake City",
      "on-site notary Clear Lake City",
    ],
  },
  {
    slug: "pasadena",
    cityName: "Pasadena",
    title: "Mobile Notary in Pasadena, TX | Houston Mobile Notary Pros",
    description:
      "Fast, friendly notarization anywhere in Pasadena—loan signings, POAs, real-estate documents, and more.",
    keywords: [
      "mobile notary Pasadena",
      "after-hours mobile notary Pasadena TX",
      "same-day notary Pasadena TX",
      "Pasadena TX loan signing agent",
      "traveling notary Pasadena",
      "24 hour notary Pasadena TX",
      "apostille services Pasadena TX",
      "mobile notary 77502",
      "notary near Strawberry Park",
      "emergency notary Pasadena",
      "weekend notary Pasadena",
      "on-site notary Pasadena",
    ],
  },
  {
    slug: "texas-city",
    cityName: "Texas City",
    title: "Mobile Notary in Texas City | Houston Mobile Notary Pros",
    description:
      "Texas City-based notary ready to travel within 20 miles of 77591 for convenient, accurate signings.",
    keywords: [
      "mobile notary Texas City",
      "after-hours mobile notary Texas City",
      "same-day notary Texas City",
      "Texas City loan signing agent",
      "traveling notary Texas City",
      "24 hour notary Texas City",
      "apostille services Texas City",
      "mobile notary 77591",
      "notary near Texas City Dike",
      "emergency notary Texas City",
      "weekend notary Texas City",
      "on-site notary Texas City",
    ],
  },
  {
    slug: "webster",
    cityName: "Webster",
    title: "Mobile Notary in Webster, TX | Houston Mobile Notary Pros",
    description: "Same-day mobile notarization across Webster and the Clear Lake area.",
    keywords: [
      "mobile notary Webster",
      "after-hours mobile notary Webster",
      "same-day notary Webster TX",
      "Webster TX loan signing agent",
      "traveling notary Webster",
      "24 hour notary Webster TX",
      "apostille services Webster TX",
      "mobile notary 77598",
      "notary near NASA Parkway",
      "emergency notary Webster",
      "weekend notary Webster",
      "on-site notary Webster",
    ],
  },
  {
    slug: "nassau-bay",
    cityName: "Nassau Bay",
    title: "Mobile Notary in Nassau Bay | Houston Mobile Notary Pros",
    description: "Professional traveling notary service for Nassau Bay residents and businesses.",
    keywords: [
      "mobile notary Nassau Bay",
      "after-hours mobile notary Nassau Bay",
      "same-day notary Nassau Bay TX",
      "Nassau Bay loan signing agent",
      "traveling notary Nassau Bay",
      "24 hour notary Nassau Bay",
      "apostille services Nassau Bay",
      "mobile notary 77058",
      "notary near Space Center Houston",
      "emergency notary Nassau Bay",
      "weekend notary Nassau Bay",
      "on-site notary Nassau Bay",
    ],
  },
  {
    slug: "seabrook",
    cityName: "Seabrook",
    title: "Mobile Notary in Seabrook, TX | Houston Mobile Notary Pros",
    description: "We come to you in Seabrook—home, marina, or office.",
    keywords: [
      "mobile notary Seabrook",
      "after-hours mobile notary Seabrook",
      "same-day notary Seabrook TX",
      "Seabrook TX loan signing agent",
      "traveling notary Seabrook",
      "24 hour notary Seabrook TX",
      "apostille services Seabrook TX",
      "mobile notary 77586",
      "notary near Kemah Boardwalk",
      "emergency notary Seabrook",
      "weekend notary Seabrook",
      "on-site notary Seabrook",
    ],
  },
  {
    slug: "clear-lake-shores",
    cityName: "Clear Lake Shores",
    title: "Mobile Notary in Clear Lake Shores | Houston Mobile Notary Pros",
    description: "Boat-friendly notary that meets you dock-side in Clear Lake Shores.",
    keywords: [
      "mobile notary Clear Lake Shores",
      "after-hours mobile notary Clear Lake Shores",
      "same-day notary Clear Lake Shores",
      "Clear Lake Shores loan signing agent",
      "traveling notary Clear Lake Shores",
      "24 hour notary Clear Lake Shores",
      "apostille services Clear Lake Shores",
      "mobile notary 77565",
      "notary near Jarboe Bayou Park",
      "emergency notary Clear Lake Shores",
      "weekend notary Clear Lake Shores",
      "on-site notary Clear Lake Shores",
    ],
  },
  {
    slug: "taylor-lake-village",
    cityName: "Taylor Lake Village",
    title: "Mobile Notary in Taylor Lake Village | Houston Mobile Notary Pros",
    description: "Prompt, precise notarization services in Taylor Lake Village.",
    keywords: [
      "mobile notary Taylor Lake Village",
      "after-hours mobile notary Taylor Lake Village",
      "same-day notary Taylor Lake Village",
      "Taylor Lake Village loan signing agent",
      "traveling notary Taylor Lake Village",
      "24 hour notary Taylor Lake Village",
      "apostille services Taylor Lake Village",
      "mobile notary 77586",
      "notary near Clear Lake Park",
      "emergency notary Taylor Lake Village",
      "weekend notary Taylor Lake Village",
      "on-site notary Taylor Lake Village",
    ],
  },
  {
    slug: "friendswood",
    cityName: "Friendswood",
    title: "Mobile Notary in Friendswood | Houston Mobile Notary Pros",
    description: "Convenient mobile notary public serving Friendswood.",
    keywords: [
      "mobile notary Friendswood",
      "after-hours mobile notary Friendswood",
      "same-day notary Friendswood",
      "Friendswood loan signing agent",
      "traveling notary Friendswood",
      "24 hour notary Friendswood",
      "apostille services Friendswood",
      "mobile notary 77546",
      "notary near Stevenson Park",
      "emergency notary Friendswood",
      "weekend notary Friendswood",
      "on-site notary Friendswood",
    ],
  },
  {
    slug: "league-city",
    cityName: "League City",
    title: "Mobile Notary in League City | Houston Mobile Notary Pros",
    description: "Trusted traveling notary for League City residents and businesses.",
    keywords: [
      "mobile notary League City",
      "after-hours mobile notary League City",
      "same-day notary League City",
      "League City loan signing agent",
      "traveling notary League City",
      "24 hour notary League City",
      "apostille services League City",
      "mobile notary 77573",
      "notary near Walter Hall Park",
      "emergency notary League City",
      "weekend notary League City",
      "on-site notary League City",
    ],
  },
  {
    slug: "kemah",
    cityName: "Kemah",
    title: "Mobile Notary in Kemah | Houston Mobile Notary Pros",
    description: "Mobile notary that meets you along the Kemah Boardwalk and beyond.",
    keywords: [
      "mobile notary Kemah",
      "after-hours mobile notary Kemah",
      "same-day notary Kemah",
      "Kemah loan signing agent",
      "traveling notary Kemah",
      "24 hour notary Kemah",
      "apostille services Kemah",
      "mobile notary 77565",
      "notary near Kemah Boardwalk",
      "emergency notary Kemah",
      "weekend notary Kemah",
      "on-site notary Kemah",
    ],
  },
  {
    slug: "la-porte",
    cityName: "La Porte",
    title: "Mobile Notary in La Porte | Houston Mobile Notary Pros",
    description: "Dependable mobile notary serving La Porte, TX.",
    keywords: [
      "mobile notary La Porte",
      "after-hours mobile notary La Porte",
      "same-day notary La Porte",
      "La Porte loan signing agent",
      "traveling notary La Porte",
      "24 hour notary La Porte",
      "apostille services La Porte",
      "mobile notary 77571",
      "notary near Sylvan Beach Park",
      "emergency notary La Porte",
      "weekend notary La Porte",
      "on-site notary La Porte",
    ],
  },
  {
    slug: "deer-park",
    cityName: "Deer Park",
    title: "Mobile Notary in Deer Park | Houston Mobile Notary Pros",
    description: "On-site notarizations throughout Deer Park, TX.",
    keywords: [
      "mobile notary Deer Park",
      "after-hours mobile notary Deer Park",
      "same-day notary Deer Park",
      "Deer Park loan signing agent",
      "traveling notary Deer Park",
      "24 hour notary Deer Park",
      "apostille services Deer Park",
      "mobile notary 77536",
      "notary near Battleground Golf Course",
      "emergency notary Deer Park",
      "weekend notary Deer Park",
      "on-site notary Deer Park",
    ],
  },
  {
    slug: "south-houston",
    cityName: "South Houston",
    title: "Mobile Notary in South Houston | Houston Mobile Notary Pros",
    description: "We travel to homes, offices, and hospitals in South Houston for fast notarizations.",
    keywords: [
      "mobile notary South Houston",
      "after-hours mobile notary South Houston",
      "same-day notary South Houston",
      "South Houston loan signing agent",
      "traveling notary South Houston",
      "24 hour notary South Houston",
      "apostille services South Houston",
      "mobile notary 77587",
      "notary near Cristo Rey Catholic Church",
      "emergency notary South Houston",
      "weekend notary South Houston",
      "on-site notary South Houston",
    ],
  },
  {
    slug: "la-marque",
    cityName: "La Marque",
    title: "Mobile Notary in La Marque | Houston Mobile Notary Pros",
    description: "Reliable notary public on wheels for La Marque.",
    keywords: [
      "mobile notary La Marque",
      "after-hours mobile notary La Marque",
      "same-day notary La Marque",
      "La Marque loan signing agent",
      "traveling notary La Marque",
      "24 hour notary La Marque",
      "apostille services La Marque",
      "mobile notary 77568",
      "notary near Gulf Greyhound Park",
      "emergency notary La Marque",
      "weekend notary La Marque",
      "on-site notary La Marque",
    ],
  },
  {
    slug: "dickinson",
    cityName: "Dickinson",
    title: "Mobile Notary in Dickinson, TX | Houston Mobile Notary Pros",
    description: "Mobile notary services for Dickinson residents—7 days a week.",
    keywords: [
      "mobile notary Dickinson",
      "after-hours mobile notary Dickinson",
      "same-day notary Dickinson",
      "Dickinson loan signing agent",
      "traveling notary Dickinson",
      "24 hour notary Dickinson",
      "apostille services Dickinson",
      "mobile notary 77539",
      "notary near Dickinson Bayou",
      "emergency notary Dickinson",
      "weekend notary Dickinson",
      "on-site notary Dickinson",
    ],
  },
  {
    slug: "santa-fe",
    cityName: "Santa Fe",
    title: "Mobile Notary in Santa Fe, TX | Houston Mobile Notary Pros",
    description: "Prompt notarization anywhere in Santa Fe and surrounding rural areas.",
    keywords: [
      "mobile notary Santa Fe",
      "after-hours mobile notary Santa Fe",
      "same-day notary Santa Fe",
      "Santa Fe TX loan signing agent",
      "traveling notary Santa Fe",
      "24 hour notary Santa Fe",
      "apostille services Santa Fe TX",
      "mobile notary 77510",
      "notary near Haak Vineyards",
      "emergency notary Santa Fe TX",
      "weekend notary Santa Fe",
      "on-site notary Santa Fe TX",
    ],
  },
  {
    slug: "galveston",
    cityName: "Galveston",
    title: "Mobile Notary in Galveston | Houston Mobile Notary Pros",
    description: "Island-wide mobile notary—hotels, cruise terminals, hospitals, and homes in Galveston.",
    keywords: [
      "mobile notary Galveston",
      "after-hours mobile notary Galveston",
      "same-day notary Galveston",
      "Galveston loan signing agent",
      "traveling notary Galveston",
      "24 hour notary Galveston",
      "apostille services Galveston",
      "mobile notary 77550",
      "notary near Pleasure Pier",
      "emergency notary Galveston",
      "weekend notary Galveston",
      "on-site notary Galveston",
    ],
  },
  {
    slug: "pearland",
    cityName: "Pearland",
    title: "Mobile Notary in Pearland | Houston Mobile Notary Pros",
    description: "From Shadow Creek Ranch to Pearland Town Center, we deliver same-day notarization across Pearland’s 77584, 77581, and 77588 ZIP codes—loan signings, POAs, wills, and more.",
    keywords: [
      "mobile notary Pearland",
      "after-hours mobile notary Pearland",
      "same-day notary Pearland TX",
      "Pearland loan signing agent",
      "traveling notary Pearland",
      "24 hour notary Pearland",
      "apostille services Pearland TX",
      "mobile notary 77584",
      "notary near Pearland Town Center",
      "emergency notary Pearland",
      "weekend notary Pearland",
      "on-site notary Pearland",
    ],
  },
  {
    slug: "alvin",
    cityName: "Alvin",
    title: "Mobile Notary in Alvin, TX | Houston Mobile Notary Pros",
    description: "Reliable mobile notary public serving Alvin 77511—real-estate closings, I-9 verifications, power of attorney notarization, and more.",
    keywords: [
      "mobile notary Alvin TX",
      "after-hours mobile notary Alvin",
      "same-day notary Alvin",
      "Alvin loan signing agent",
      "traveling notary Alvin",
      "24 hour notary Alvin",
      "apostille services Alvin TX",
      "mobile notary 77511",
      "notary near Nolan Ryan Museum",
      "emergency notary Alvin",
      "weekend notary Alvin",
      "on-site notary Alvin",
    ],
  },
  {
    slug: "manvel",
    cityName: "Manvel",
    title: "Mobile Notary in Manvel, TX | Houston Mobile Notary Pros",
    description: "Fast loan-signing and document notarization throughout Manvel 77578—including evening and weekend appointments.",
    keywords: [
      "mobile notary Manvel TX",
      "after-hours mobile notary Manvel",
      "same-day notary Manvel",
      "Manvel loan signing agent",
      "traveling notary Manvel",
      "24 hour notary Manvel",
      "apostille services Manvel TX",
      "mobile notary 77578",
      "notary near Manvel Town Center",
      "emergency notary Manvel",
      "weekend notary Manvel",
      "on-site notary Manvel",
    ],
  },
  {
    slug: "hitchcock",
    cityName: "Hitchcock",
    title: "Mobile Notary in Hitchcock, TX | Houston Mobile Notary Pros",
    description: "On-site notarization in Hitchcock 77563—power of attorney, real estate, and more, delivered to your door or Jack Brooks Park.",
    keywords: [
      "mobile notary Hitchcock TX",
      "after-hours mobile notary Hitchcock",
      "same-day notary Hitchcock",
      "Hitchcock loan signing agent",
      "traveling notary Hitchcock",
      "24 hour notary Hitchcock",
      "apostille services Hitchcock TX",
      "mobile notary 77563",
      "notary near Jack Brooks Park",
      "emergency notary Hitchcock",
      "weekend notary Hitchcock",
      "on-site notary Hitchcock",
    ],
  },
  {
    slug: "brazoria-county",
    cityName: "Brazoria County",
    title: "Mobile Notary in Brazoria County | Houston Mobile Notary Pros",
    description: "County-wide traveling notary—Alvin, Manvel, Pearland, and rural areas—covering affidavits, estate docs, and loan packages.",
    keywords: [
      "mobile notary Brazoria County",
      "after-hours mobile notary Brazoria County",
      "same-day notary Brazoria County",
      "Brazoria County loan signing agent",
      "traveling notary Brazoria County",
      "24 hour notary Brazoria County",
      "apostille services Brazoria County",
      "notary near Brazoria National Wildlife Refuge",
      "emergency notary Brazoria County",
      "weekend notary Brazoria County",
      "on-site notary Brazoria County",
      "mobile notary Brazoria TX",
    ],
  },
]

export function getServiceAreaBySlug(slug: string): ServiceArea | undefined {
  return SERVICE_AREAS.find((a) => a.slug === slug)
}
