#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Prevent secrets & obvious security issues from entering the repo
npx --no-install gitleaks protect --staged --verbose

# Basic code quality gate (fast)
pnpm lint -s 